# -*- coding: utf-8 -*-
"""2024_0315_estadisticos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gOMkwWTIsVe8IG-ImqZjQA4-caPTThax
"""

def promedio(V):

    k= len(V)
    # Verificamos si el vector está vacío
    if k == 0:
        return 0

    # Inicializamos la suma
    suma = 0

    # Sumamos todos los elementos del vector usando un ciclo for
    for i in range (k):
        a=V[i]
        suma += a

    # Calculamos el promedio dividiendo la suma por la cantidad de elementos
    promedio = suma / k

    return promedio


    # Ejemplo de uso de la función promedio
V = [1, 2, 3, 4, 5]
resultado = promedio(V)
print("El promedio de los datos es:", resultado)

from math import sqrt

def des_est(V):
  acumulador=0
  k=len(V)
  prom = promedio(V)

  for i in range (k):
        resta=V[i]-prom
        acumulador= acumulador+(resta**2)

  div = acumulador/k
  desv=sqrt(div)

  return desv


    # Ejemplo de uso de la función desviacion estandar
V = [1, 2, 3, 4, 5]
resultado = des_est(V)
print("La desviacion estandar de los datos es:", resultado)

def varianza (V):
  desv= des_est(V)
  var=desv*desv
  return var


V = [1, 2, 3, 4, 5]
resultado = varianza(V)
print("La varianza de los datos es:", resultado)

